### ISSUE TITLE
Missing link in README.

### ISSUE THREAD

**Issue by Arco-Dielhof** [overwolf/sample-app#26]
This references a link, that is not there.
![image](https://user-images.githubusercontent.com/56220993/123628815-cec61b80-d813-11eb-9a61-9f6ef856cdd3.png)

**Comment by Arco-Dielhof** [comment]
After forking and checking the README, it appears the link is broken due to an extra set of brackets. Removing the extra set should fix it.

![image](https://user-images.githubusercontent.com/56220993/123629359-7d6a5c00-d814-11eb-818a-98b27cfd9a3b.png)

**Comment by eransharv** [comment]
thanks @Arco-Dielhof I fixed the broken link.
