### ISSUE TITLE
Calling minimize starts a process

### ISSUE THREAD

**Issue by gabrielmicko** [overwolf/sample-app#33]
Hey,

I think this is an issue:
I pretty much reused your sample app. When I click on my DESKTOP window and minimize the app it calls this function in the BG screen. Calling `this.windowsService.minimize(kWindowNames.IN_GAME)` boots up the ingame process. I think this is really unwanted behaviour.
My desktop and in-game apps look the same they have the same code. I inject the Advertisement SDK when the app is opened. Because of this it happens that the SDK code runs twice at the same time and I happen to fail the review process.

Do you guys think that there should be a handle in this function to only call minimize when the window is really open?

https://github.com/overwolf/sample-app/blob/master/native/windows/background/background-controller.js
```
  async minimize() {
    await Promise.all([
      this.windowsService.minimize(kWindowNames.DESKTOP),
      this.windowsService.minimize(kWindowNames.IN_GAME)
    ]);
  }
```

**Comment by eransharv** [comment]
Hey @gabrielmicko and thank you. We pushed a fix.

**Comment by gabrielmicko** [comment]
Awesome
