### ISSUE TITLE
setRequiredFeatures undefiend when gap fails to register

### ISSUE THREAD

**Issue by gabrielmicko** [overwolf/sample-app#36]
![Screenshot 2021-10-31 205049](https://user-images.githubusercontent.com/4391461/139599227-a6835afb-f98e-45c8-addb-cb4ac420be95.png)
![Screenshot 2021-10-31 205105](https://user-images.githubusercontent.com/4391461/139599228-3f678a59-16ec-4adf-9145-d8842e1acce1.png)

**Comment by eransharv** [comment]
@antonk777 FYI

**Comment by antonk777** [comment]
Fixed in #38, thanks!
