### ISSUE TITLE
Deprecate getRunningGameInfo

### ISSUE THREAD

**Issue by gabrielmicko** [overwolf/sample-app#40]
Would you mind updating getRunningGameInfo to getRunningGameInfo2 all over the codebase?

https://github.com/overwolf/sample-app/blob/04ff136e4eef8608b67cba5b8c97efb098429bfa/native/scripts/services/running-game-service.js#L36

**Comment by eransharv** [comment]
@antonk777 please review it

**Comment by eransharv** [comment]
@gabrielmicko getRunningGameInfo2  introduced in v0.188 so we will update the code when this version will be phased to 100% of the users.
